# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db79e53c98003ec6745ef58b75ae3b8d3f1e570b3d0c292532f73ced58f2923c802b59f7b83b761e454023adbba30bde0d5ae52d3e8fb0c4e527b2165b7dd82d

test:
  secret_key_base: 1825ca8fafb1c23c71217ec4dc984f2ce4c47df970db2eab8a4ca5a9c83a33f74e0f8c335f0e3ebbb3a112580c030035518921024f285129280095661f349c8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
